<?php
/**
 * @var \Study\Mod1\Block\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<form class="input-form" id="input-form-id" method="post"
      action="<?= $escaper->escapeUrl($block->getUrl($block->getActionUrl())) ?>">
    <!--<div class="search-widget">
    <input type="text" id="search-input" name="sku"/>
        <ul class="search-result-list"></ul>
    </div>-->
    <div data-bind="scope:'searchProduct'">
        <!-- ko template : getTemplate() -->
        <!-- /ko -->
    </div>
        <?php if ($block->isQtyEnabled()): ?>
            <label for="qty-input"><?= $escaper->escapeHtml(__('Количесвто:')) ?></label>
            <input type="text" name="qty" id="qty-input" value="<?= $block->getQtyNumber() ?>"/>
        <?php endif; ?>
        <?= $block->getChildHtml('Study.additional'); ?>
    <input type="submit" class="button-submit-data"/>
</form>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "searchProduct": {
                        "component": "Study_Mod1/js/koSearchProduct",
                        "template": "Study_Mod1/koSearchProduct"
                    }
                }
            }
        }
    }


</script>

<!--<script type="text/x-magento-init">
    {
        ".search-widget": {
        "Study_Mod1/js/widgetAutoComplete": {
            "minChars": 3
            }
        }
    }
</script>-->
