<?php
/**
 * @var \Study\Mod1\Block\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<form class="input-form" id="input-form-id" method="post"
      action="<?= $escaper->escapeUrl($block->getUrl($block->getActionUrl())) ?>">
    <input type="text" name="sku"/>
    <?php if ($block->isQtyEnabled()): ?>
        <input type="text" name="qty" value="<?= $block->getQtyNumber() ?>"/>
    <?php endif; ?>
    <?= $block->getChildHtml('Study.additional'); ?>
    <input type="submit" class="button-submit-data"/>
</form>
