<?php
/**
 * @var \Study\Mod1\Block\Index $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="jquery-buttons">
    <input type="submit" class="button-footer-hide" value="Close Footer"/>
    <input type="submit" class="button-change-border-color" value="Change border color"/>
</div>
<script>
    require(['jquery'], function ($) {
        $('.button-footer-hide').on('click', function (e) {
            $('.page-footer').hide()
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Study_Mod1/js/border-color": {}
        }
    }
</script>
